defaults:
  - net: gta5_source
_target_: src.models.ttda_module.DIGA
cfg:
  bn_lambda: 0.9
  proto_lambda: 0.8
  fusion_lambda: 0.4 # best
  confidence_threshold: 0.9
  top_k: 1.0 # best
  proto_rho: 0.5 # best
  bn_bank_size: 32
  prototype_bank_size: 32
